In [1]:
import numpy as np
import torch
from var_control.optimization import *

In [2]:
n=50000

In [3]:
X = np.random.rand(1, n+1)
X = X[0]
X = np.sort(X, axis=-1)
X[n] = X[n-1]
test_loss = X.astype('float64')

In [4]:
np.mean(test_loss)

0.5022137207662785

In [5]:
b = np.arange(1, test_loss.shape[-1] + 1) / test_loss.shape[-1]

quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda()
)

tensor([0.5022], device='cuda:0')

In [6]:
quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda(),
    beta_min=0.25,
    beta_max=0.75
)

tensor([0.5031], device='cuda:0')

In [7]:
quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda(),
    beta_min=0.75,
    beta_max=1.0
)

tensor([0.8769], device='cuda:0')

In [8]:
quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda(),
    weighted=True
)

tensor([0.3346], device='cuda:0')

In [16]:
quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda(),
    weighted=True,
    weight_d=3
)

tensor([0.2006], device='cuda:0')

In [12]:
q = (0.5)/(0.6)

In [13]:
q*quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda(),
    beta_min=0.25,
    beta_max=0.75
)+(1-q)*quantile_based_loss(
    torch.Tensor(test_loss).view(1,-1).cuda(), 
    torch.Tensor(b).cuda(),
    beta_min=0.9,
    beta_max=1.0
)

tensor([0.5777], device='cuda:0')